import type {
  LegacyClub as Club,
  LegacyMatch as Match,
  LegacyPlayer as Player,
  LegacyPost as Post,
  LegacyTransfer as Transfer,
  LegacyUser as User,
} from '@/types'

// Mock Users
export const mockUsers: User[] = [
  {
    id: '1',
    name: 'Alex Turner',
    handle: 'alexturner',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Alex',
    bio: 'Football enthusiast | Manchester supporter',
    followers: 2850,
    following: 456,
    isFollowing: false,
  },
  {
    id: '2',
    name: 'Jordan Silva',
    handle: 'jordansilva',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Jordan',
    bio: 'Fan of beautiful football',
    followers: 1240,
    following: 892,
    isFollowing: true,
  },
  {
    id: '3',
    name: 'Sam Johnson',
    handle: 'samjohnson',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Sam',
    bio: 'Tactical analysis | Strategy nerd',
    followers: 3120,
    following: 234,
    isFollowing: false,
  },
  {
    id: '4',
    name: 'Riley Chen',
    handle: 'rileychen',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Riley',
    bio: 'Live match coverage specialist',
    followers: 5670,
    following: 123,
    isFollowing: true,
  },
]

// Mock Clubs
export const mockClubs: Club[] = [
  {
    id: 'mc',
    name: 'Manchester City',
    logo: 'https://api.dicebear.com/7.x/shapes/svg?seed=Manchester',
    country: 'England',
    followers: 45000,
  },
  {
    id: 'lr',
    name: 'Liverpool',
    logo: 'https://api.dicebear.com/7.x/shapes/svg?seed=Liverpool',
    country: 'England',
    followers: 42000,
  },
  {
    id: 'mu',
    name: 'Manchester United',
    logo: 'https://api.dicebear.com/7.x/shapes/svg?seed=Manchester2',
    country: 'England',
    followers: 38000,
  },
  {
    id: 'ar',
    name: 'Arsenal',
    logo: 'https://api.dicebear.com/7.x/shapes/svg?seed=Arsenal',
    country: 'England',
    followers: 35000,
  },
  {
    id: 'rm',
    name: 'Real Madrid',
    logo: 'https://api.dicebear.com/7.x/shapes/svg?seed=RealMadrid',
    country: 'Spain',
    followers: 52000,
  },
]

// Mock Players
export const mockPlayers: Player[] = [
  {
    id: 'p1',
    name: 'Erling Haaland',
    number: 9,
    position: 'Striker',
    nationality: 'Norwegian',
    age: 24,
    club: mockClubs[0],
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Haaland',
    followers: 8900,
    stats: {
      appearances: 34,
      goals: 27,
      assists: 5,
    },
  },
  {
    id: 'p2',
    name: 'Mohamed Salah',
    number: 11,
    position: 'Right Wing',
    nationality: 'Egyptian',
    age: 32,
    club: mockClubs[1],
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Salah',
    followers: 9200,
    stats: {
      appearances: 30,
      goals: 19,
      assists: 8,
    },
  },
  {
    id: 'p3',
    name: 'Bukayo Saka',
    number: 7,
    position: 'Left Wing',
    nationality: 'English',
    age: 23,
    club: mockClubs[3],
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Saka',
    followers: 6400,
    stats: {
      appearances: 28,
      goals: 14,
      assists: 11,
    },
  },
  {
    id: 'p4',
    name: 'Vinicius Junior',
    number: 7,
    position: 'Left Wing',
    nationality: 'Brazilian',
    age: 24,
    club: mockClubs[4],
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Vinicius',
    followers: 7800,
    stats: {
      appearances: 32,
      goals: 18,
      assists: 9,
    },
  },
  {
    id: 'p5',
    name: 'Declan Rice',
    number: 41,
    position: 'Midfielder',
    nationality: 'English',
    age: 26,
    club: mockClubs[3],
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Rice',
    followers: 5200,
    stats: {
      appearances: 26,
      goals: 2,
      assists: 1,
    },
  },
]

// Mock Matches
export const mockMatches: Match[] = [
  {
    id: 'm1',
    homeTeam: mockClubs[0],
    awayTeam: mockClubs[1],
    date: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000),
    status: 'upcoming',
    league: 'Premier League',
  },
  {
    id: 'm2',
    homeTeam: mockClubs[3],
    awayTeam: mockClubs[2],
    date: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
    status: 'finished',
    homeScore: 2,
    awayScore: 1,
    league: 'Premier League',
  },
  {
    id: 'm3',
    homeTeam: mockClubs[4],
    awayTeam: mockClubs[0],
    date: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000),
    status: 'upcoming',
    league: 'Champions League',
  },
  {
    id: 'm4',
    homeTeam: mockClubs[3],
    awayTeam: mockClubs[1],
    date: new Date(Date.now() - 67 * 60 * 1000),
    status: 'live',
    homeScore: 2,
    awayScore: 1,
    league: 'Premier League',
    liveMinute: 67,
  },
]

// Mock Posts
export const mockPosts: Post[] = [
  {
    id: 'post1',
    author: mockUsers[0],
    content: 'Incredible performance from Haaland today! The composure in front of goal is just different.',
    likes: 234,
    replies: 45,
    reposts: 78,
    shares: 23,
    isLiked: false,
    createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000),
    relatedPlayer: mockPlayers[0],
  },
  {
    id: 'post2',
    author: mockUsers[1],
    content: 'That defensive display from Arsenal was textbook. Rice and the back line were immense.',
    likes: 456,
    replies: 89,
    reposts: 234,
    shares: 67,
    isLiked: true,
    createdAt: new Date(Date.now() - 4 * 60 * 60 * 1000),
    relatedMatch: mockMatches[1],
  },
  {
    id: 'post3',
    author: mockUsers[2],
    content: 'Looking at the tactical adjustments in the second half... fascinating stuff.',
    likes: 189,
    replies: 34,
    reposts: 56,
    shares: 12,
    isLiked: false,
    createdAt: new Date(Date.now() - 6 * 60 * 60 * 1000),
  },
  {
    id: 'post4',
    author: mockUsers[3],
    content: 'City vs Liverpool this weekend - this is the match we\'ve all been waiting for!',
    likes: 678,
    replies: 123,
    reposts: 345,
    shares: 89,
    isLiked: false,
    createdAt: new Date(Date.now() - 1 * 60 * 60 * 1000),
    relatedMatch: mockMatches[0],
  },
  {
    id: 'post5',
    author: mockUsers[0],
    content: 'Salah\'s footwork in that sequence was just poetry in motion.',
    likes: 234,
    replies: 45,
    reposts: 78,
    shares: 23,
    isLiked: false,
    createdAt: new Date(Date.now() - 8 * 60 * 60 * 1000),
    relatedPlayer: mockPlayers[1],
  },
]

// Mock Transfers
export const mockTransfers: Transfer[] = [
  {
    id: 'tf1',
    player: mockPlayers[0],
    fromClub: mockClubs[1],
    toClub: mockClubs[0],
    fee: '€60M',
    date: new Date(2023, 6, 15),
  },
  {
    id: 'tf2',
    player: mockPlayers[2],
    fromClub: mockClubs[3],
    toClub: mockClubs[3],
    fee: 'academy graduate',
    date: new Date(2022, 5, 10),
  },
]
